language: php
dist: trusty
sudo: false

php:
- 7.1
- 7.2

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini || true

before_script:
- composer self-update
- composer install

script:
- php vendor/bin/phpunit